---
abstract: 'Check @INC once for modules that you want but may not have'
author:
  - 'Daniel Muey <http://drmuey.com/cpan_contact.pl>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Want
no_index:
  directory:
    - t
    - inc
requires:
  File::Path::Tiny: 0
  File::Spec: 0
  File::Temp: 0
  Test::Carp: 0
  Test::More: 0
version: 0.6
